//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolBox2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToolBoxEntities : DbContext
    {
        public ToolBoxEntities()
            : base("name=ToolBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COORDINADOR> COORDINADOR { get; set; }
        public virtual DbSet<EQUIPOS> EQUIPOS { get; set; }
        public virtual DbSet<Error_Falla> Error_Falla { get; set; }
        public virtual DbSet<HERRA_PROY> HERRA_PROY { get; set; }
        public virtual DbSet<HERRAMIENTA> HERRAMIENTA { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MODELO> MODELO { get; set; }
        public virtual DbSet<Pre_Error> Pre_Error { get; set; }
        public virtual DbSet<PROYECTO> PROYECTO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TECN_PROYECTO> TECN_PROYECTO { get; set; }
        public virtual DbSet<TECNICO> TECNICO { get; set; }
    }
}
