//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolBox2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HERRA_PROY
    {
        public int Id { get; set; }
        public Nullable<int> Id_Proy { get; set; }
        public Nullable<int> Id_Herr { get; set; }
        public string Descripcion { get; set; }
    
        public virtual HERRAMIENTA HERRAMIENTA { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
