//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolBox2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECN_PROYECTO
    {
        public int Id { get; set; }
        public Nullable<int> Id_proy { get; set; }
        public Nullable<int> Id_tecn { get; set; }
    
        public virtual PROYECTO PROYECTO { get; set; }
        public virtual TECNICO TECNICO { get; set; }
    }
}
